#!/usr/bin/env node
/**
 * `next dev` reads .env from the Next app directory, but this repo keeps one
 * .env at the monorepo root (compose consumes it as a whole). Without this,
 * every DB-backed route 500s on "Invalid environment variables".
 *
 * The root .env addresses the shared infra by its compose service names, which
 * only resolve inside the network. A dev server on the host reaches the same
 * services through their published ports, so rewrite those hosts to localhost.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Compose service names that tools/infa-basic also publishes on the host. */
const CONTAINER_HOSTS = ['postgres', 'redis', 'minio']

const APPS = ['apps/web', 'apps/portal']

export function toHostReachable(value) {
  return CONTAINER_HOSTS.reduce(
    (current, host) =>
      current.replace(
        new RegExp(`(//|@)${host}(:\\d+)`, 'g'),
        (_match, prefix, port) => `${prefix}localhost${port}`,
      ),
    value,
  )
}

export function buildDevEnv(rootEnv) {
  return rootEnv
    .split('\n')
    .map((line) => {
      const match = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line)
      return match ? `${match[1]}=${toHostReachable(match[2])}` : line
    })
    .join('\n')
}

function main() {
  const rootEnv = readFileSync(join(repoRoot, '.env'), 'utf8')
  const banner = [
    '# GENERATED by scripts/sync-dev-env.mjs — do not edit.',
    '# Edit the root .env instead, then re-run `pnpm dev` (or the script).',
    '# Container hostnames are rewritten to localhost for host-run dev servers.',
    '',
  ].join('\n')

  for (const app of APPS) {
    writeFileSync(join(repoRoot, app, '.env.local'), banner + buildDevEnv(rootEnv))
    console.log(`sync-dev-env: wrote ${app}/.env.local`)
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main()
